language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
    - .cache

# override default command since it doesn't skip checkstyle
install:
  - tools/install-repackaged

script:
  - mvn -nsu -T 1.5C -D environment=test -P '!findbugs' verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
