language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
    - .cache

# override default command since it doesn't skip checkstyle
install:
  - tools/install-repackaged

script:
  - mvn -nsu -T 1 -D threadCount=2 -D perCoreThreadCount=false -D environment=test -P '!findbugs,codecov' verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
