port: 8080

refreshClusterSchedule: "0 */5 * * * ?"

cluster:
  useLocal: false
  tags:
    site: sto
  protocols:
    - type: http
    - type: nativerpc
  capabilities:
    - WRITE
    - QUERY
  discovery:
    type: static
    nodes:
      - nativerpc://localhost

metrics:
  backends:
    - type: datastax
      group: heroic
      seeds:
        - sto3-heroiccassandra-a1.spotify.net
        - sto3-heroiccassandra-a2.spotify.net
        - sto3-heroiccassandra-a3.spotify.net
      pools:
        readQueueSize: 100000

metadata:
  backends:
    - type: elasticsearch
      backendType: v1
      connection:
        clusterName: heroic-sto
        index:
          type: rotating
          pattern: heroic-metadata-b-v1-%s
        seeds:
          - sto3-heroicmetadata-a1.spotify.net
          - sto3-heroicmetadata-a2.spotify.net
          - sto3-heroicmetadata-a3.spotify.net

suggest:
  backends:
    - type: elasticsearch
      backendType: v1
      connection:
        clusterName: heroic-suggest-sto-b
        index:
          type: rotating
          pattern: heroic-suggest-b-v1-%s
        seeds:
          - sto3-heroicsuggest-bdm1.spotify.net
          - sto3-heroicsuggest-bdm2.spotify.net
          - sto3-heroicsuggest-bdm3.spotify.net

ingestion:
  updateMetrics: false
  updateMetadata: false
  updateSuggestions: false
