metrics:
  backends:
    - type: datastax
      group: heroic
      seeds:
        - sto3-heroiccassandra-a1.spotify.net
        - sto3-heroiccassandra-a2.spotify.net
        - sto3-heroiccassandra-a3.spotify.net
