metrics:
  backends:
    - type: datastax
      schema:
        type: legacy
      seeds:
        - awsuse1-heroiccassandra-a1.shared.cloud.spotify.net
        - awsuse1-heroiccassandra-a2.shared.cloud.spotify.net
        - awsuse1-heroiccassandra-a3.shared.cloud.spotify.net
