metrics:
  backends:
    - type: datastax
      group: heroic
      seeds:
        - sjc1-heroiccassandra2-a1.spotify.net
        - sjc1-heroiccassandra2-a2.spotify.net
        - sjc1-heroiccassandra2-a3.spotify.net
