metrics:
  backends:
    - type: datastax
      schema:
        type: legacy
      seeds:
        - lon6-heroiccassandra-a1.spotify.net
        - lon6-heroiccassandra-a2.spotify.net
        - lon6-heroiccassandra-a3.spotify.net
