metrics:
  backends:
    - type: datastax
      schema:
        type: legacy
      seeds:
        - gcb2-heroiccassandra-a1.gcb2.spotify.net
        - gcb2-heroiccassandra-a2.gcb2.spotify.net
        - gcb2-heroiccassandra-a3.gcb2.spotify.net
