port: 8080

metrics:
  backends:
    - type: datastax
      group: heroic
      seeds:
        - sjc1-heroiccassandra-a1.spotify.net
        - sjc1-heroiccassandra-a2.spotify.net
        - sjc1-heroiccassandra-a3.spotify.net

ingestion:
  updateMetrics: false
  updateMetadata: false
  updateSuggestions: false
