metrics:
  backends:
    - type: datastax
      group: heroic
      seeds:
        - ash2-heroiccassandra-a1.spotify.net
        - ash2-heroiccassandra-a2.spotify.net
        - ash2-heroiccassandra-a3.spotify.net
